export const listCustomer = [
  {
    Accountid: "011C200370     ",
    AccountName: "Vũ Thị Minh Nguyệt",
    Start_code: "VGT            ",
    Start_code_date: "1/7/22",
    Hold_max_code: "SD3            ",
    Hold_Day: "228",
    Position_max_code: "ACB            ",
    Position_min_code: "SCR            ",
    end_code: "HPG            ",
    end_code_date: "5/24/22",
  },
  {
    Accountid: "011C003311",
    AccountName: "Võ Quốc Thịnh",
    Start_code: "TYA",
    Start_code_date: "9/30/22",
    Hold_max_code: "TYA            ",
    Hold_Day: "185",
    Position_max_code: "TYA            ",
    Position_min_code: "TYA            ",
    end_code: "TYA",
    end_code_date: "9/30/22",
  },
  {
    Accountid: "011C054711     ",
    AccountName: "Trần Quý Hào",
    Start_code: "HT1            ",
    Start_code_date: "4/12/22",
    Hold_max_code: "HT1",
    Hold_Day: "164",
    Position_max_code: "HT1",
    Position_min_code: "VSC            ",
    end_code: "VSC            ",
    end_code_date: "4/19/22",
  },
  {
    Accountid: "011C207906",
    AccountName: "NGUYỄN VĂN DỰ",
    Start_code: "NVL",
    Start_code_date: "11/28/22",
    Hold_max_code: "HBC            ",
    Hold_Day: "228",
    Position_max_code: "NVL",
    Position_min_code: "HBC            ",
    end_code: "NVL",
    end_code_date: "12/8/22",
  },
  {
    Accountid: "011C001300",
    AccountName: "Nguyễn Thanh Tâm",
    Start_code: "HPG            ",
    Start_code_date: "1/6/22",
    Hold_max_code: "HPG            ",
    Hold_Day: "215",
    Position_max_code: "HPG            ",
    Position_min_code: "DHM            ",
    end_code: "POW",
    end_code_date: "12/2/22",
  },
  {
    Accountid: "011C100401     ",
    AccountName: "Tạ Thị Tính",
    Start_code: "HPG            ",
    Start_code_date: "1/10/22",
    Hold_max_code: "NBC            ",
    Hold_Day: "228",
    Position_max_code: "HPG",
    Position_min_code: "RSHB           ",
    end_code: "HPG            ",
    end_code_date: "5/25/22",
  },
  {
    Accountid: "011C002115",
    AccountName: "Nguyễn Việt Hùng",
    Start_code: "VTO            ",
    Start_code_date: "3/11/22",
    Hold_max_code: "VTO            ",
    Hold_Day: "228",
    Position_max_code: "VTO            ",
    Position_min_code: "PXL            ",
    end_code: "PXL",
    end_code_date: "12/6/22",
  },
  {
    Accountid: "011C332794",
    AccountName: "LÊ VĂN CHÍNH",
    Start_code: "AMD            ",
    Start_code_date: "1/6/22",
    Hold_max_code: "ITA            ",
    Hold_Day: "91",
    Position_max_code: "APG",
    Position_min_code: "HBC            ",
    end_code: "APG",
    end_code_date: "12/15/22",
  },
  {
    Accountid: "011C117878",
    AccountName: "Lê Huy Cường",
    Start_code: "CII            ",
    Start_code_date: "1/4/22",
    Hold_max_code: "PLP",
    Hold_Day: "228",
    Position_max_code: "FPT            ",
    Position_min_code: "RPLP           ",
    end_code: "HAP",
    end_code_date: "8/22/22",
  },
  {
    Accountid: "011C022889",
    AccountName: "Nguyễn Thành Nhân",
    Start_code: "ITA            ",
    Start_code_date: "1/4/22",
    Hold_max_code: "HCM            ",
    Hold_Day: "228",
    Position_max_code: "STB            ",
    Position_min_code: "ITA            ",
    end_code: "HCM",
    end_code_date: "12/20/22",
  },
];
