export const listCustomer = [
  {
    Accountid: "011C545711     ",
    AccountName: "NGUYỄN THỊ TRÚC HẠ",
    EMailAddress: "NGUYENTHITRUCHA00@GMAIL.COM",
    Start_code: "ITA            ",
    Start_code_date: "04/01/2022",
    Hold_max_code: "HBC            ",
    Hold_Day: "228",
    Position_max_code: "TVC            ",
    Position_min_code: "SPP            ",
    end_code: "NAF            ",
    end_code_date: "09/05/2022",
  },
  {
    Accountid: "011C060693",
    AccountName: "BÙI VIỆT NAM",
    EMailAddress: "MRBVNAM@GMAIL.COM",
    Start_code: "HAG",
    Start_code_date: "28/09/2022",
    Hold_max_code: "CSM            ",
    Hold_Day: "228",
    Position_max_code: "HAG",
    Position_min_code: "RSHB           ",
    end_code: "HAG",
    end_code_date: "10/11/2022",
  },
  {
    Accountid: "011C130505",
    AccountName: "VŨ ĐÌNH GIÁP",
    EMailAddress: "VUGIAPND@GMAIL.COM",
    Start_code: "VND            ",
    Start_code_date: "10/01/2022",
    Hold_max_code: "VND            ",
    Hold_Day: "224",
    Position_max_code: "VND            ",
    Position_min_code: "RVIX           ",
    end_code: "VND",
    end_code_date: "14/11/2022",
  },
  {
    Accountid: "011C544205",
    AccountName: "ĐÀO VIỆT PHƯƠNG",
    EMailAddress: "VIETPHUONG1310@GMAIL.COM",
    Start_code: "BID            ",
    Start_code_date: "14/01/2022",
    Hold_max_code: "CTG",
    Hold_Day: "228",
    Position_max_code: "PVS            ",
    Position_min_code: "DCM            ",
    end_code: "PDR",
    end_code_date: "21/12/2022",
  },
  {
    Accountid: "011C018622",
    AccountName: "Trương Phạm Thục Uyên",
    EMailAddress: "tpthucuyen@gmail.com",
    Start_code: "CFPT2103       ",
    Start_code_date: "05/01/2022",
    Hold_max_code: "SSI            ",
    Hold_Day: "203",
    Position_max_code: "SSI            ",
    Position_min_code: "RSSI           ",
    end_code: "SCR",
    end_code_date: "26/10/2022",
  },
  {
    Accountid: "011C542900",
    AccountName: "Bùi Thị Như Tâm",
    EMailAddress: "tam06hbt@gmail.com",
    Start_code: "GVR",
    Start_code_date: "28/10/2022",
    Hold_max_code: "GVR",
    Hold_Day: "25",
    Position_max_code: "GVR",
    Position_min_code: "GVR",
    end_code: "GVR",
    end_code_date: "01/12/2022",
  },
  {
    Accountid: "011C130589     ",
    AccountName: "PHẠM THỊ KIỀU OANH",
    EMailAddress: "OANH.PHAMKIEU67@GMAIL.COM",
    Start_code: "DLG            ",
    Start_code_date: "29/04/2022",
    Hold_max_code: "DLG            ",
    Hold_Day: "134",
    Position_max_code: "DLG            ",
    Position_min_code: "DLG            ",
    end_code: "DLG            ",
    end_code_date: "19/07/2022",
  },
  {
    Accountid: "011C127531",
    AccountName: "ĐẶNG QUỐC MINH ĐĂNG",
    EMailAddress: "DANG.QUOC.MINH.DANG@GMAIL.COM",
    Start_code: "STB",
    Start_code_date: "10/10/2022",
    Hold_max_code: "POW",
    Hold_Day: "33",
    Position_max_code: "HPG",
    Position_min_code: "POW",
    end_code: "POW",
    end_code_date: "07/12/2022",
  },
  {
    Accountid: "011C130515     ",
    AccountName: "MAI THỊ TẦN",
    EMailAddress: "MAITHITAN111@GMAIL.COM",
    Start_code: "PVD            ",
    Start_code_date: "15/03/2022",
    Hold_max_code: "DXG",
    Hold_Day: "228",
    Position_max_code: "TTF",
    Position_min_code: "MBB",
    end_code: "GMD            ",
    end_code_date: "18/04/2022",
  },
  {
    Accountid: "011C544578     ",
    AccountName: "HÀ VĂN HỒNG",
    EMailAddress: "HONGHV.VIETVUONG@GMAIL.COM",
    Start_code: "AAA            ",
    Start_code_date: "12/05/2022",
    Hold_max_code: "AAA            ",
    Hold_Day: "14",
    Position_max_code: "DIG            ",
    Position_min_code: "HAG            ",
    end_code: "ABB            ",
    end_code_date: "30/05/2022",
  },
];
